spring:
  datasource:
    url: jdbc:mysql://localhost:3307/reservation?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springboot
    password: 'springboot0!'

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  mustache:
    suffix: .html

